# fog_credentials.yml
default:
  aws_access_key_id: 'AKIAIRGQJ37RAEJTCRQA'       # required
  aws_secret_access_key: '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'       # required
  region: 'us-east-1'  # optional, defaults to 'us-east-1'