# fog_credentials.yml
default:
  aws_access_key_id: '0N32ZH1TB8N1VEVXMQR2'       # required
  aws_secret_access_key: 'OTiKz9yH8VpGzbhPR5LmDBcyEl2d+LJRKKtMTsb3'       # required
  region: 'us-east-1'  # optional, defaults to 'us-east-1'